version = 1

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["react"]

[[analyzers]]
name = "python"
enabled = true

[analyzers.meta]
runtime_version = "3.x.x"

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true
