name: Test, Build, and Deploy
# This workflow will run on all pushes
on: [push]

env:
    WEBAPP_NAME: ent # set this to your application's name
    WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: "16.13.0" # set this to the node version to use
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    CI: false
jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            # - name: Cache node modules # Likely unnecessary
            #   uses: actions/cache@v2
            #   env:
            #       cache-name: cache-node-modules
            #   with:
            #       # npm cache files are stored in `~/.npm` on Linux/macOS
            #       path: ~/.npm
            #       key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            #       restore-keys: |
            #           ${{ runner.os }}-build-${{ env.cache-name }}-
            #           ${{ runner.os }}-build-
            #           ${{ runner.os }}-
            - uses: actions/checkout@v2
            - name: Use Node version ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  #registry-url: "https://npm.pkg.github.com"
            - name: Install and configure
              run: |
                  # Check the node version
                  node --version
                  corepack enable
                  # setup for commiting back to this branch
                  git config --global user.name 'GitHub Actions Builder'
                  git config --global user.email 'github.action.builder@users.noreply.github.com'
                  # Install the project, then...
                  yarn init-project
                  yarn install --immutable
            - name: Build
              run: |
                  # Prevent lint from failing the ci build
                  rm -rf .eslintrc.json
                  yarn build
            - name: Run Tests
              run: yarn test
